# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './tasks/task5.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(673, 302)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.file1URL = QtWidgets.QLabel(self.centralwidget)
        self.file1URL.setGeometry(QtCore.QRect(10, 10, 51, 16))
        self.file1URL.setObjectName("file1URL")
        self.progressBar1 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar1.setGeometry(QtCore.QRect(10, 60, 361, 21))
        self.progressBar1.setProperty("value", 24)
        self.progressBar1.setObjectName("progressBar1")
        self.file1UrlInput = QtWidgets.QLineEdit(self.centralwidget)
        self.file1UrlInput.setGeometry(QtCore.QRect(10, 30, 361, 20))
        self.file1UrlInput.setObjectName("file1UrlInput")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(400, 20, 261, 241))
        self.startButton.setObjectName("startButton")
        self.file2UrlInput = QtWidgets.QLineEdit(self.centralwidget)
        self.file2UrlInput.setGeometry(QtCore.QRect(10, 120, 361, 20))
        self.file2UrlInput.setObjectName("file2UrlInput")
        self.file1URL_2 = QtWidgets.QLabel(self.centralwidget)
        self.file1URL_2.setGeometry(QtCore.QRect(10, 100, 51, 16))
        self.file1URL_2.setObjectName("file1URL_2")
        self.progressBar2 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar2.setGeometry(QtCore.QRect(10, 150, 361, 21))
        self.progressBar2.setProperty("value", 24)
        self.progressBar2.setObjectName("progressBar2")
        self.file1URL_3 = QtWidgets.QLabel(self.centralwidget)
        self.file1URL_3.setGeometry(QtCore.QRect(10, 190, 51, 16))
        self.file1URL_3.setObjectName("file1URL_3")
        self.file3UrlInput = QtWidgets.QLineEdit(self.centralwidget)
        self.file3UrlInput.setGeometry(QtCore.QRect(10, 210, 361, 20))
        self.file3UrlInput.setObjectName("file3UrlInput")
        self.progressBar3 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar3.setGeometry(QtCore.QRect(10, 240, 361, 21))
        self.progressBar3.setProperty("value", 24)
        self.progressBar3.setObjectName("progressBar3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.file1URL.setText(_translate("MainWindow", "File 1 URL: "))
        self.startButton.setText(_translate("MainWindow", "Start downloading!"))
        self.file1URL_2.setText(_translate("MainWindow", "File 1 URL: "))
        self.file1URL_3.setText(_translate("MainWindow", "File 1 URL: "))
